[Project]
"Start time" = "2020-1-1 00:00:00.0"
"Simulation duration (min)" = 5
"Loadshape start time" = "2020-1-1 00:00:00.0"
"Step resolution (sec)" = 60.0
"Max Control Iterations" = 50
"Error tolerance" = 0.001
"Control mode" = "Static"
"Disable PyDSS controllers" = false
"Simulation Type" = "QSTS"
"Project Path" = "./examples/external_interfaces"
"Active Project" = "pydss_project"
"Active Scenario" = ""
"DSS File" = "Master_Spohn_existing_VV.dss"
"DSS File Absolute Path" = false
"Return Results" = false

[[Project.Scenarios]]
name = "helics"
post_process_infos = []

# [[Project.Scenarios]]
# name = "python"
# post_process_infos = []

# [[Project.Scenarios]]
# name = "socket"
# post_process_infos = []

[Exports]
"Export Mode" = "byClass"
"Export Style" = "Single file"
"Export Format" = "csv"
"Export Compression" = false
"Export Elements" = true
"Export Data Tables" = false
"Export Data In Memory" = false
"HDF Max Chunk Bytes" = 32768
"Export Event Log" = true
"Log Results" = true

[Frequency]
"Enable frequency sweep" = false
"Fundamental frequency" = 60
"Start frequency" = 1.0
"End frequency" = 15.0
"frequency increment" = 2.0
"Neglect shunt admittance" = false
"Percentage load in series" = 50.0

[Helics]
"Co-simulation Mode" = true
"Iterative Mode" = true
"Error tolerance" = 0.1
"Max co-iterations" = 20
"Broker" = "127.0.0.1"
"Broker port" = 23404
"Federate name" = "PyDSS"
"Time delta" = 0.01
"Core type" = "zmq"
Uninterruptible = true
"Helics logging level" = 5

[Logging]
"Logging Level" = "DEBUG"
"Log to external file" = true
"Display on screen" = true
"Clear old log file" = false
"Pre-configured logging" = false

[MonteCarlo]
"Number of Monte Carlo scenarios" = -1

[Plots]
"Create dynamic plots" = false
"Open plots in browser" = true
