"Log Results" = true
"Return Results" = false
"Export Mode" = "byClass"
"Export Style" = "Single file"

"Create dynamic plots" = false
"Open plots in browser" = true

"Start Year" = 2017
"Start Day" = 1
"Start Time (min)" = 0.0
"End Day" = 1
"End Time (min)" = 1439.0
"Date offset" = 0
"Step resolution (sec)" = 900.0
"Max Control Iterations" = 15
"Error tolerance" = 0.001
"Control mode" = "Time"
"Disable PyDSS controllers" = false
"Simulation Type" = "QSTS"
"Project Path" = ""
"Active Project" = ""
"Active Scenario" = ""
"DSS File" = ""

"Co-simulation Mode" = false
"Federate name" = "PyDSS"
"Time delta" = 0.01
"Core type" = "zmq"
"Uninterruptible" = true
"Helics logging level" = 5

"Enable frequency sweep" = false
"Fundamental frequency" = 60
"Start frequency" = 1.0
"End frequency" = 15.0
"frequency increment" = 2.0
"Neglect shunt admittance" = false
"Percentage load in series" = 50.0

"Logging Level" = "WARNING"
"Log to external file" = false
"Display on screen" = true
"Clear old log file" = false

"Number of Monte Carlo scenarios" = -1

