[1]
Class = "PVSystems"
Property = "kVA"
Distribution = "norm"
Parameters = "[10,0.1]"
useWildCard = false
Wildcard = ""	
isList = false
ListLength = 0
isInteger = false

[2]
Class = "PVSystems"
Property = "pf"
Distribution = "uniform"
Parameters = "[0.95,0.03]"
useWildCard = false
Wildcard = ""	
isList = false
ListLength = 0
isInteger = false

[3]
Class = "Loads"
Property = "kW"
Distribution = "beta"
Parameters = "[1,2]"
useWildCard = false
Wildcard = ""	
isList = false
ListLength = 0
isInteger = false

[4]
Class = "Loadshape"
Property = "mult"
Distribution = "weibull_min"
Parameters = "[1,5]"
useWildCard = true
Wildcard = "pvmult"	
isList = true
ListLength = 100
isInteger = false

[5]
Class = "Loadshape"
Property = "mult"
Distribution = "gamma"
Parameters = "[1,2]"
useWildCard = true
Wildcard = "loadmult"	
isList = true
ListLength = 100
isInteger = false
