[Project]
"Start Year" = 2017
"Start Day" = 1
"Start Time (min)" = 0.0
"End Day" = 1
"End Time (min)" = 1439.0
"Date offset" = 0
"Step resolution (sec)" = 900.0
"Max Control Iterations" = 50
"Error tolerance" = 0.001
"Control mode" = "Static"
"Disable PyDSS controllers" = false
"Simulation Type" = "QSTS"
"Project Path" = "C:\\Users\\alatif\\Desktop\\PyDSS_2.0\\PyDSS\\examples"
"Active Project" = "custom_contols"
"Active Scenario" = "base_case"
"DSS File" = "Master_Spohn_existing_VV.dss"
"DSS File Absolute Path" = false
"Return Results" = false

[[Project.Scenarios]]
name = "base_case"
post_process_infos = []

[Exports]
"Export Mode" = "byClass"
"Export Style" = "Single file"
"Export Format" = "h5"
"Export Compression" = false
"Export Iteration Order" = "ValuesByPropertyAcrossElements"
"Export Elements" = false
"Export Data Tables" = true
"Export Data In Memory" = true
"HDF Max Chunk Bytes" = 32768
"Export Event Log" = true
"Log Results" = true
"Result Container" = "ResultData"

[Frequency]
"Enable frequency sweep" = false
"Fundamental frequency" = 60
"Start frequency" = 1.0
"End frequency" = 15.0
"frequency increment" = 2.0
"Neglect shunt admittance" = false
"Percentage load in series" = 50.0

[Helics]
"Co-simulation Mode" = false
"Federate name" = "PyDSS"
"Time delta" = 0.01
"Core type" = "zmq"
Uninterruptible = true
"Helics logging level" = 5

[Logging]
"Logging Level" = "INFO"
"Log to external file" = true
"Display on screen" = true
"Clear old log file" = false
"Pre-configured logging" = false

[MonteCarlo]
"Number of Monte Carlo scenarios" = -1

[Plots]
"Create dynamic plots" = false
"Open plots in browser" = true
